magfest/guests

- .gitignore
- bands/configspec.ini
- bands/models.py
- bands/site_sections/band_admin.py
- bands/site_sections/bands.py
- bands/templates/band_admin/band_info.html
- bands/templates/band_admin/index.html
- bands/templates/bands/index.html
- bands/templates/bands/panel.html
- bands/templates/bands/stage_plot.html
This has two main feature additions (plus a little code cleanup):
- Stage plots can now be uploaded.  Chaney needs to tell me what words to put to explain what we want, but I added some reasonable sounding text for now.
- Bands can be linked to events on the schedule, which will be useful when we implement the "Final Confirmation" step.
> Uploading stage plots

- bands/automated_emails.py
- bands/configspec.ini
- bands/models.py
- bands/site_sections/band_admin.py
- bands/site_sections/bands.py
- bands/templates/band_admin/band_info.html
- bands/templates/band_admin/index.html
- bands/templates/bands/agreement.html
- bands/templates/bands/charity.html
- bands/templates/bands/index.html
- bands/templates/bands/rock_island.html
- bands/templates/emails/band_agreement_reminder.txt
- bands/templates/emails/band_bio_reminder.txt
- bands/templates/emails/band_charity_reminder.txt
- bands/templates/emails/band_merch_reminder.txt
- bands/templates/emails/band_panel_reminder.txt
- bands/templates/emails/band_stage_plot_reminder.txt
- bands/templates/emails/band_w9_reminder.txt
This adds two new items to the checklist and implements automated reminder emails.  It requires the following modifications to the database, which I've already done on the staging and production servers:
```sql
ALTER TABLE band ADD COLUMN merch INTEGER DEFAULT NULL;
ALTER TABLE band ADD COLUMN charity INTEGER DEFAULT NULL;
ALTER TABLE band ADD COLUMN charity_donation TEXT NOT NULL DEFAULT '';
```
> Merch, charity, and reminder emails

- bands/automated_emails.py
- bands/configspec.ini
- bands/models.py
- bands/site_sections/band_admin.py
- bands/site_sections/bands.py
- bands/templates/band_admin/band_info.html
- bands/templates/band_admin/index.html
- bands/templates/bands/agreement.html
- bands/templates/bands/bio.html
- bands/templates/bands/charity.html
- bands/templates/bands/index.html
- bands/templates/bands/panel.html
- bands/templates/bands/rock_island.html
- bands/templates/bands/stage_plot.html
- bands/templates/bands/w9.html
Fixes #11. Fixes https://github.com/magfest/bands/issues/19. Fixes https://github.com/magfest/bands/issues/21.
> Break apart schema into one class per step

- bands/templates/bands/index.html
Fixes #13 and fixes #14 by simply showing steps only if their deadline is set. Also adds a bandextra.html for adding more steps.
> Use deadlines to hide/show steps

- bands/automated_emails.py
- bands/configspec.ini
- bands/models.py
- bands/site_sections/band_admin.py
- bands/site_sections/bands.py
- bands/templates/band_admin/band_info.html
- bands/templates/band_admin/index.html
- bands/templates/bands/agreement.html
- bands/templates/bands/bio.html
- bands/templates/bands/charity.html
- bands/templates/bands/index.html
- bands/templates/bands/panel.html
- bands/templates/bands/rock_island.html
- bands/templates/bands/stage_plot.html
- bands/templates/bands/w9.html
Fixes #15.
All the code in here has already been reviewed while merging into this branch, this is just a last chance to review the whole set of changes and +1 it.
> Make bands plugin extensible

- bands/site_sections/bands.py
- bands/templates/bands/index.html
- bands/templates/bands/merch.html
- since not all events will have the concept of rock island (area where magfest sells merch for bands), rename the page
> rename rock_island.html to merch.html

- bands/configspec.ini
- bands/site_sections/bands.py
- bands/templates/bands/index.html
- bands/templates/bands/merch.html
Ability to turn on/off:
- Rock island text/dropdown option/validation
- Requirement that bands agree to sit at a table for 8 hours a day
NOTE: builds on an existing Pull Request (does not merge to master, merges to rename_rock_island_page branch)
> Make band merch page configurable

- bands/templates/emails/band_notification.txt
Fixes https://github.com/magfest/bands/issues/37.
> Fix typo in band_notification

- bands/models.py
- bands/templates/band_admin/band_info.html
Fixes https://github.com/magfest/ubersystem/issues/1863
A bunch of variables were renamed and this part didn't get updated, easy fix.
> Fix w9 display

- bands/site_sections/band_admin.py
- bands/templates/band_admin/index.html
Wrote a remove band function to solve issue #1912 on /ubersystem repo.  
Didn't make the return HTML as pretty as it could be. Sorry :/ it works nice if you reload though :P
> Add remove function to band_admin

- bands/automated_emails.py
This pull request directly depends on [#2386](https://github.com/magfest/ubersystem/pull/2386).
> Fixes #2383: Adds static ident arg to each AutomatedEmail instance

- bands/__init__.py
merge after https://github.com/magfest/ubersystem/pull/1849
> Implement new python-based menu format

- bands/site_sections/bands.py
some email and menu stuff.  this would be automatically merged normally, was throwing it in here for testing purposes
> merge master into jinja2 branch

- bands/models.py
I missed something in the last PR.
> Actually fix default `status` property

- bands/templates/bands/bio.html
- bands/templates/bands/stage_plot.html
- bands/templates/bands/w9.html
Fixes https://github.com/magfest/ubersystem/issues/2566 -- bands can now see the files they previously uploaded, causing less confusion.
> Show uploaded files to the band that uploaded them

- bands/site_sections/band_admin.py
Fixes https://github.com/magfest/bands/issues/66 by using the _required_message helper function to check for all the input fields on the admin's Band Info page. We return a form error if any of them are blank.
> Add 'required' checks for admins editing Band Info

- alembic/versions/6aef7396c197_adds_more_band_info_columns.py
- bands/models.py
- bands/templates/band_admin/band_info.html
- bands/templates/band_admin/index.html
- bands/templates/bandbase.html
- bands/templates/bands/agreement-base.html
- bands/templates/bands/bio.html
- bands/templates/bands/charity.html
- bands/templates/bands/index.html
- bands/templates/bands/merch.html
- bands/templates/bands/panel.html
- bands/templates/bands/stage_plot.html
- bands/templates/bands/w9.html
- bands/templates/checklist/band_agreement_deadline.html
- bands/templates/checklist/band_badge_deadline.html
- bands/templates/checklist/band_bio_deadline.html
- bands/templates/checklist/band_charity_deadline.html
- bands/templates/checklist/band_merch_deadline.html
- bands/templates/checklist/band_panel_deadline.html
- bands/templates/checklist/band_w9_deadline.html
- bands/templates/checklist/stage_agreement_deadline.html
Changes checklist wording and sorts checklist by date. Uses the new macros in a lot of places, to get the nice auto-linking of urls.
Also adds two columns: 
- `band_panel.other_tech_needs`
- `band_bio.teaser_song_url`
**Note**: this depends on https://github.com/magfest/ubersystem/pull/2787
> Fixes #85: Changes checklist wording and sorts checklist by date

- bands/site_sections/band_admin.py
- bands/tests/test_band_admin.py
Requested by Super Music dept.
> Make new bands use Guest badges instead of Attendee badges

- alembic/versions/a1a5bd54b2aa_add_autograph_interview_and_travel_plan_.py
- guests/config.py
- guests/configspec.ini
- guests/models.py
- guests/site_sections/guests.py
- guests/templates/checklist/autograph_deadline.html
- guests/templates/checklist/guest_bio_deadline.html
- guests/templates/checklist/guest_panel_deadline.html
- guests/templates/checklist/interview_deadline.html
- guests/templates/checklist/travel_plans_deadline.html
- guests/templates/guest_admin/guest_info.html
- guests/templates/guest_admin/index.html
- guests/templates/guests/autograph.html
- guests/templates/guests/guest_agreement.html
- guests/templates/guests/interview.html
- guests/templates/guests/travel_plans.html
Adds new checklist steps as requested by our Guest department, and ties the Panels step (for guests) to the panels plugin. Also implements many wording changes.
> Integrate guest plugin with panels plugin and customize guest checklist

- guests/automated_emails.py
- guests/configspec.ini
- guests/models.py
- guests/site_sections/guests.py
- guests/templates/checklist/guest_badges_deadline.html
- guests/templates/checklist/guest_bio_deadline.html
- guests/templates/checklist/guest_charity_deadline.html
- guests/templates/checklist/guest_merch_deadline.html
- guests/templates/checklist/guest_panel_deadline.html
- guests/templates/emails/guest_checklist_reminder.html
- guests/templates/guests/band_agreement.html
- guests/templates/guests/guest_agreement.html
Fixes a couple bugs found by the Guest department, too!
> Make even more text changes for guests

- guests/templates/emails/guest_checklist_reminder.html
Updates the text of the email, per the guest department
> Edit Guest checklist email

- .gitignore
- alembic/versions/9e3e15a7cf59_adds_rock_island_inventory.py
- guests/__init__.py
- guests/configspec.ini
- guests/model_checks.py
- guests/models.py
- guests/site_sections/guest_admin.py
- guests/site_sections/guests.py
- guests/templates/checklist/autograph_deadline.html
- guests/templates/checklist/band_merch_deadline.html
- guests/templates/checklist/bio_deadline.html
- guests/templates/checklist/charity_deadline.html
- guests/templates/checklist/interview_deadline.html
- guests/templates/checklist/merch_deadline.html
- guests/templates/checklist/panel_deadline.html
- guests/templates/checklist/stage_plot_deadline.html
- guests/templates/checklist/taxes_deadline.html
- guests/templates/checklist/travel_plans_deadline.html
- guests/templates/guest_admin/band_info.html
- guests/templates/guest_admin/guest_info.html
- guests/templates/guest_admin/rock_island.html
- guests/templates/guestbase.html
- guests/templates/guests_common.html
- guests/templates/guests_macros.html
Fixes #93.
This is a big pull request. It may be easiest to review by actually running the code locally.
> Fixes #93: Adds Rock Island merch info collection

- guests/models.py
- guests/templates/checklist/band_merch_deadline.html
- guests/templates/guests_macros.html
Just hit these errors testing on staging4, so I wanna merge this quick.
> Adds some "None" checks in the templates, fixes errors encountered with a newly created group

- guests/automated_emails.py
- guests/templates/emails/guest_checklist_announce.html
- guests/templates/emails/guest_checklist_reminder.html
The Guests department wanted the reminder emails to be a little different from the first email.
> Add separate template for reminding guests about their checklist

- guests/config.py
- guests/configspec.ini
- guests/models.py
- guests/templates/checklist/band_merch_deadline.html
- guests/templates/checklist/guest_merch_deadline.html
- guests/templates/checklist/merch_deadline.html
Our guest department wants guests to use Rock Island, so I've made it configurable.
No dev machine means this hasn't been tested. :( Sorry.
> Allow configurable group types to use Rock Island

- guests/templates/checklist/merch_deadline.html
> Seems like everwhere in our codebase we use the term "Cancel" and have the button on the right

- alembic/versions/9e3e15a7cf59_adds_rock_island_inventory.py
- alembic/versions/f619fbd56912_rename_band_tables_to_guest_tables.py
- guests/configspec.ini
- guests/models.py
- guests/site_sections/guest_admin.py
- guests/templates/checklist/merch_deadline.html
- guests/templates/guest_admin/rock_island.html
> Fixes magfest/ubersystem#2887: Adds rock island inventory status to admin and checklist pages

- guests/automated_emails.py
This is useful in conjunction with https://github.com/magfest/ubersystem/pull/2972
> send performer checklist FROM music department email
