bands/templates/band_admin/band_info.html, bands/templates/band_admin/index.html
Admins were getting confused because a band which doesn't need a W9 was showing up with their "W9" step unchecked, which made it seem like there was work that needed to be done.  I've changed it so that a check shows up for that step for bands not receiving payment who therefore don't need a W9.  I also added a note about this on the Band Info admin page.
=> added clarification to W9 step

bands/templates/band_admin/index.html
Minor tweak to the W9 stuff I implemented earlier today.  While technically it is true that non-bands have nothing left to do w.r.t. a W9, it's confusing and misleading to list a Y in that column.
=> non-bands no longer show up as Y in the W9 column

bands/site_sections/band_admin.py
This was crashing and took a while to figure out what exactly was going wrong. (we didn't have ```concerts``` in ```[event_locations]```)
Splitting up the code this way means if someone runs into the same issue later when trying to setup a new uber instance, it'll be more obvious what's going wrong.
We probably should check for c.CONCERTS in c.EVENT_LOCATION_OPTS, maybe will do that in a while.
=> split up code for readability

bands/templates/bands/agreement-base.html
the double ```<br>```s will go away with the real styling, works for now
fix hardcoded text, re-arrange small stuff to make things look a little nicer
=> minor text fixes for agreement

bands/configspec.ini, bands/models.py
- this should probably be a config setting because magprime will be very different from the other events (due to 2 stage flip flopping)
- this is a sensible default for regular 1-stage events
=> change soundcheck / performance times to more real-world defaults

bands/models.py, bands/templates/band_admin/band_info.html
- calculations were resulting in incorrect times due to not subtracting setup time
- this calculation also would have broken for bands starting at non-schedule interval times (at :00 or :30 on the hour)
- this is still not a bad idea, but, the schedule itself needs to support bands starting at arbitrary times, and currently doesn't
- also, for main magfest, we usually setup one block for all bands called i.e. "Friday Concerts" so the band plugin would think the performance  time was 6 hours for each band
fixes #39
=> disable autofill of band performance length from schedule

bands/models.py
implement 'band' property for Attendee in order to tell if this attendee is associated with a band
useful for a bunch of stuff, we're going to use it in magstock plugin to tell it that bands get free food.
=> updated: add band property to Attendee band plugin mixin

bands/templates/band_admin/band_info.html, bands/templates/bands/agreement-base.html
Per Mike P's request
- If an event is associated with the band, then the contract will reflect that time
- If there is no event associated with the band, then the contract will say "more info coming later on start time"
- Add some helpful text
=> Add band start times to band agreement

bands/models.py, bands/site_sections/band_admin.py
requires magfest/ubersystem#1890
Make band plugin use relative URLs for purely web-based stuff, and use the new functionality in base ubersystem to create absolute urls when we have no other choice, such as for the CSV export of band information, or email text generation.
=> use relative URLs for band info

bands/site_sections/bands.py
Fixes https://github.com/magfest/bands/issues/32. A leftover parameter in the function was resetting the band info's ID to None, making it try to create a new band_info object every time it was saved.
=> Stop setting band_info id to None every time

bands/templates/band_admin/band_info.html, bands/templates/band_admin/index.html
Now that we have Jinja2 templating, we can use the variable admin_area to control what gets included in child templates, rather than inheriting from a different template. We're implementing that now.
=> Remove base-admin.html

bands/site_sections/band_admin.py, bands/templates/band_admin/add_band.html, bands/templates/band_admin/index.html, bands/tests/test_band_admin.py, test-defaults.ini
This branch will add a page under `band_admin/add_band` which will automate the workflow as described in issue #51. 
This also adds a button to `band_admin/index`. Please please please suggest changes to the UI or code. Teamwork makes the dreamwork. Also, I am unsure what the unit test for this would look like code-wise. Still getting the hang of them.
=> Add page to decrease steps required to create band

bands/automated_emails.py, bands/models.py, bands/templates/band_admin/band_info.html, bands/templates/band_admin/index.html, bands/templates/bands/index.html
Fixes https://github.com/magfest/ubersystem/issues/2543 by passing specific representations of items' statuses to the template, instead of just a boolean indicating whether or not the item exists. We can still use these as booleans for the band checklist, because they will only be falsey if the step isn't completed.
=> Improve band_admin index page to list status of items

bands/templates/band_admin/index.html
The template would return a 500 error if a group without a band was listed. Whoops.
=> Fix 500 error in band_admin index

bands/models.py
Reverts default `status` property to work as the `completed` property did before. The new way is causing email errors.
=> Fix 500 errors when sending band emails

bands/models.py, bands/site_sections/bands.py, bands/tests/models/test_band.py
Fixes https://github.com/magfest/bands/issues/77 by:
1) fixing a bug where the view's name was used because we forgot to provide a disposition to our file serving function, and 
2) adding a custom filename to use so admins don't get the random filenames uploaded by bands (e.g., band_name_bio_pic.png vs my_best_selfie.png)
=> Add custom, admin-friendly filenames to downloaded files

alembic/versions/edd7b60ea4b4_add_per_band_hotel_room_count.py, bands/models.py, bands/site_sections/band_admin.py, bands/templates/band_admin/band_info.html, bands/templates/bands/agreement-base.html
fixes #57 
Previously, our contracts always assumed we were offering hotel rooms to each band.  Now, make this configurable for 0 or more hotel rooms.
What it looks like:
This also affects the band contract and the "hotel" section will be hidden if we are offering no rooms.
=> allow admins to specify # of hotel rooms for band contracts

bands/tests/test_band_admin.py, test-defaults.ini
Must be merged after https://github.com/magfest/ubersystem/pull/2711. Converts this plugin to using the syntax needed for the new MultiChoice ribbons.
=> Convert to using a MultiChoice column for ribbons

bands/site_sections/bands.py, bands/templates/emails/band_w9_reminder.txt
The w9 url only accepts `band_id` as a parameter. The problem with that is we've been sending out emails that use `id` as a parameter instead of `band_id`. So when the band tries to click on the URL in the email they received, they are rewarded with a nice big error.
I'd like to just switch the email to use the right parameter, but we've ALREADY sent those emails out. They exist in the wild. So, I've changed the w9 method to accept both `band_id` AND `id`.
I'm going to sleep, so if anyone happens to review this before I wake up, please change it as you see fit, merge it, and deploy it on my behalf. Because we have users out there clicking on bum links.
=> Changes band w9 URL to accept both band_id and id

bands/templates/emails/band_agreement_reminder.txt, bands/templates/emails/band_bio_reminder.txt, bands/templates/emails/band_charity_reminder.txt, bands/templates/emails/band_merch_reminder.txt, bands/templates/emails/band_panel_reminder.txt, bands/templates/emails/band_stage_plot_reminder.txt
All emails to bands were using `id` as a parameter, but most of the URLs they pointed to actually only accept `band_id`. We'd better fix this before any more emails get approved or we'll have to do more PRs like https://github.com/magfest/bands/pull/83.
=> Update emails to bands to use the correct URLs

guests/models.py, guests/templates/checklist/bio_deadline.html, guests/templates/checklist/charity_deadline.html, guests/templates/checklist/guest_bio_deadline.html, guests/templates/checklist/info_deadline.html, guests/templates/checklist/panel_deadline.html, guests/templates/checklist/stage_plot_deadline.html, guests/templates/guest_admin/band_info.html
There was a bug in the getattr function that would split the attribute too much, causing travel_plans_status to always return 'N/A' because it ended up checking a nonexistent property. This fixes that, plus changes all the old status calls to use the new functionality.
=> Fix travel_plans_status and convert all status calls to _status

guests/automated_emails.py
I forgot to set this to the guest email address, so guests were getting this automated email from the regsupport@ address. Whoops!
=> Fix sender of the guest checklist email

guests/templates/guest_admin/rock_island.html, guests/templates/guests_common.html, guests/templates/guests_macros.html
The little image previews in the Rock Island table actually use the full resolution image for the `src`. That's not ideal, but it's okay if you only have a few images on the screen at a given time.
I realized that the full /guest_admin/rock_island page will end up displaying every promo image at the full resolution. Huge bandwidth/performance hog.
The *correct* solution would be to implement true image thumbnails. That could be a significant development task, so instead I opted to suppress the image previews on the full rock_island page.
Looks like this now:
=> Suppresses the Rock Island promo image on the full /guest_admin/rock_island page

guests/model_checks.py
I think it would be better if a band could choose to use Rock Island services without immediately knowing what merch they're selling. By removing the empty inventory validation check, a band can choose Rock Island, and then come back later to update their inventory.
=> Removes empty inventory validation check

guests/models.py
Since we no longer consider an empty inventory an invalid state, the model check inside of `status()` is no longer needed. Plus, returning `None` from `status()` was breaking our guests table:
=> Reverts GuestMerch.status to not use models_checks.py

guests/templates/guest_admin/index.html
- this page in particular was blooming in page size due to whitespace
- manually trim whitespace on guest page
noticed this page was loading really slow on my phone, but pageload time on server was fine.
the file being sent was 2.0MB and mostly whitespace.  adding in the '-' characters more aggressively strips whitespace.  not sure if this will help too much but, definitely trims the page a ton.
before(left), after(right):
=> aggressively trim more whitespace
